# Generated by Django 3.2.24 on 2024-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_item_category_product_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
